# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: xanderboy2001.github.io
title: Untitled Life Sim Dev Log
description: >- # this means to ignore newlines until "baseurl:"
  A basic development log for a currently-untitled life simulator game.
  I'm hoping this blog helps keep me motivated as I use this game to hone
  my computer science and game development skills.
baseurl: "/UntitledLifeSim/" # the subpath of your site, e.g. /blog
url: "https://xanderboy2001.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima
remote_theme: jekyll/minima
plugins:
  #- jekyll-feed
  - jekyll-remote-theme
minima:
  skin: auto
  author:
    name: Alex Christian
    email: alexanderechristian@gmail.com
  social_links:
    - platform: github
      user_url: "https://github.com/xanderboy2001"
    - platform: mastodon
      user_url: "https://mastodon.social/@xanderboy2001"
    - platform: bluesky
      user_url: "https://bsky.app/profile/xanderboy2001.bsky.social"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
